---
language: python
python:
  - "2.7"
  - "3.6"

services:
  - docker

install:
  - pip install molecule == 2.22
  - pip install docker

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
