---
- name: config | Configuring daemons
  template:
    backup: yes
    src: etc/frr/daemons.j2
    dest: /etc/frr/daemons
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart frr
    - start frr

- name: config | Configuring vtysh.conf
  template:
    backup: yes
    src: etc/frr/vtysh.conf.j2
    dest: /etc/frr/vtysh.conf
    owner: frr
    group: frr
    mode: u=rw,g=r,o=
  become: true
  notify:
    - restart frr
    - start frr

- name: config | Configuring debian.conf
  template:
    backup: yes
    src: etc/frr/debian.conf.j2
    dest: /etc/frr/debian.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart frr
    - start frr
  when: ansible_os_family == "Debian"

- name: config | Configuring zebra.conf
  template:
    backup: yes
    src: etc/frr/zebra.conf.j2
    dest: /etc/frr/zebra.conf
    owner: frr
    group: frr
    mode: u=rw,g=r,o=
  become: true
  register: _frr_zebra_configured
  notify:
    - restart frr
    - start frr

# We need to flush here in case interfaces are configured in zebra.conf
- name: config | Flusing Handlers
  meta: flush_handlers

# We need to rediscover facts if interfaces are initially configured in zebra.conf
- name: config | Rediscovering Facts
  setup:
  when: _frr_zebra_configured['changed']

- name: config | Configuring FRR
  template:
    backup: yes
    src: etc/frr/frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart frr
    - start frr
