---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: Vagrant
platforms:
  - name: centos7
    image: centos:7
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: debian8
  #   image: debian:8
  #   privileged: true
  # - name: debian9
  #   image: debian:9
  #   privileged: true
  - name: ubuntu1404
    image: ubuntu:14.04
    privileged: true
  - name: ubuntu1604
    image: ubuntu:16.04
    privileged: true
  - name: ubuntu1804
    image: ubuntu:18.04
    privileged: true
  # - name: ubuntu1904
  #   image: ubuntu:19.04
  #   privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["204", "503", "602"]
verifier:
  name: testinfra
  lint:
    name: flake8
